### ISSUE TITLE
Formalizing Working Guidelines

### ISSUE THREAD

**Issue by ramirezfranciscof** [nanolebrero/lio#46]
I have recently been told that for some time now the branch rc has been used as the default branch to incorporate new features. I am experiencing some problems with it now, but I will open a different issue for that; I wanted to discuss a bit about organization.

Based on what I've been told about why this has happened, I started looking for how other people deal with this concerns and found an interesting article that seems very interesting: http://nvie.com/posts/a-successful-git-branching-model/. I would recommend to come up with a similar set of explicit politics based on the ones presented there and put it inside the README or in a similar and visible place.

(I would also recommend actually opening a new "develop" branch, either from master on rc, since I think rc was originally one of chad's "private" branches)

**Comment by ramirezfranciscof** [comment]
I will summarize the general scheme here:

(*) There are two permanent branches: develop and master (which holds release versions).
(*) Feature branches emerge from develop and merge into develop; these are our working branches to include new features for the program.
(*) Release branches are created from develop when we want to incorporate the new features as they are into the release version. Version number is decided, remaining bugs are fixed, etc. This will merge into both master and develop.
(*) Hotfix branches are created from master, are used for fixing urgent bugs in the release version, and is then merged back into master and develop.


Some ideas I consider noteworthy:
(*) Release and develop are separated, so we have more freedom then to break develop. This is not to say that it is ok for develop to BE broken: problems with develop should be dealt with as soon as possible, and if it takes a significant amount of time, the commit should be "reverted" and the issue should be dealt with separately. But it is healthy to take advantage of the fact that each of us may be working in a separate part of the code to find each other's bugs, and this is achieved by frequently merging into develop our new and tested features, and frequently incorporating the changes other make in develop in our own branches.
(*) Merging with "--no-ff" to keep the main branches (master and develop) cleaner (this will already happen when there are merge conflicts, we might as well have it be the standard for every merge). This shows a clearer picture of how features and fixes are added into the main develop branch. I can later make a cheatsheet with the commands for each procedure for quick reference.
(*) Tagging each version of master: I mention this because I still couldn't find out what is the great advantage of doing this, since every commit of master is a new version. Perhaps it is not necessary for us to do this. What perhaps could be healthier is to be more organized with our versioning (as far as I know there is none at all).

What do you think about it then? Any comments? Should we start applying this?

**Comment by ramirezfranciscof** [comment]
@nanolebrero @segmentat10nfault @williamagudelo82 @chopkins906 does anybody have any kind of problem with this new working guidelines? Because if we all agree, I can start the develop branch today and make a file with the rules and from now on we abide by this.

Some extra notes:
(1) I will be starting develop from master instead of rc so that @chopkins906 can work on finding the bug with no rush. Once we are sure rc is working again, it should be fairly easy to merge it into develop; then chad can keep rc as a branch of his own if it serves him any purpose or just delete it.
(2) Does anyone know which open branches have been left by manuel and juan pablo? We should probably identify them, take whatever we can from them, and then close them. I've been told that due to their new contract with google overlord they can't even talk to us about their stuff anymore, so even if there is usefull stuff there it would be more costly to try to interpret it than to just start from scratch.

**Comment by nanolebrero** [comment]
Hi everybody, I agree with Francisco about the need of a strategy for
development.
I think that the branch for development should start from RC branch,
because are many important and complicated changes merged on it (even some
made by Manuel and Juan Pablo).
I hope to close the RC branch soon so we can give some stable version with
the new stuff for the users.
There are many branches made by Manuel and Juan pablo, I think we can close
most of them (the important stuff are in RC branch), however I can ask to
them what we should do. I think that they ask in google for permission to
work with Lio but I don't know the answer.

Nano



2015-07-10 9:35 GMT-03:00 ramirezfranciscof <notifications@github.com>:

**Comment by chopkins906** [comment]
Hi, I think the whole develop/master scheme sounds fine.

However, my thought is that we need to get a stable release version up first like Nano mentions (the rc branch was supposed to be a "release candidate" I think, it wasn't my branch to start with).  Once the release is up and master is updated with it, then I think that would be a good launching point to start the develop branch.  For the time being, I think rc should be treated like the "develop" branch, since it has all of the various merges that were meant for the release.

On that note: @nanolebrero is there anything more going into the release as far as new features? Or once any issues are fixed with the current rc code, that will be the release?

**Comment by williamagudelo82** [comment]
Hi !
I am in agree with @nanolebrero  & @chopkins906:  as I understand the rc branch is "the most complete" Lio version at this time.
The OpenShell option is not yet available in rc branch (because of multicore code) and I don't know when this is ready (nano and me think before end of year).
In general, I am in agreement with this work scheme ;)

**Comment by ramirezfranciscof** [comment]
Ok, then I'll wait until the new version is released and meanwhile people can still work on rc (though personally I'll be working from a branch updated with master since the current problems don't allow me to run tests on attempted modifications).

In the meantime I will try to put together a "reference" with this guidelines and common git commands or other issues (I've been playing a little bit with the wiki, I think it could be a good place to put it). Also, this may be a good time to discuss versioning...if anybody knows something about it. This week I'm going to try to search the internet for common practices on this.

**Comment by fedepedron** [comment]
A new working scheme was proposed by fork/pull requests to a new LIO repository. The main repository will still contain three branches: develop --> beta --> release

**Comment by ramirezfranciscof** [comment]
New issue #65 created for this.
